# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  username: alex@dormdish.com
  password: 100892Steph
  database: DormDish_development

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
  
production:
    adapter: postgresql
    username: alex@dormdish.com
    password: 100892Steph
    database: DormDish_production


